# Generated by Django 3.1.5 on 2021-01-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['name'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='programminglenguage',
            options={'ordering': ['name'], 'verbose_name': 'Linguagem de Programação', 'verbose_name_plural': 'Linguagens de Programação'},
        ),
        migrations.AlterField(
            model_name='programminglenguage',
            name='learning_difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], max_length=20),
        ),
    ]
